package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.PpCreditsRule;
import org.linlinjava.litemall.db.domain.PpCreditsRuleExample;

public interface PpCreditsRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    long countByExample(PpCreditsRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    int deleteByExample(PpCreditsRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    int insert(PpCreditsRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    int insertSelective(PpCreditsRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    PpCreditsRule selectOneByExample(PpCreditsRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    PpCreditsRule selectOneByExampleSelective(@Param("example") PpCreditsRuleExample example, @Param("selective") PpCreditsRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    List<PpCreditsRule> selectByExampleSelective(@Param("example") PpCreditsRuleExample example, @Param("selective") PpCreditsRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    List<PpCreditsRule> selectByExample(PpCreditsRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    PpCreditsRule selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") PpCreditsRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    PpCreditsRule selectByPrimaryKey(Integer id);

    PpCreditsRule getRule();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PpCreditsRule record, @Param("example") PpCreditsRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PpCreditsRule record, @Param("example") PpCreditsRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PpCreditsRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_credits_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PpCreditsRule record);
}
